let Quotes = ["There's only one thing I hate more than lying: skim milk. Which is water that's lying about being milk.",
"The less I know about other people's affairs, the happier I am. I'm not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.",
"Dear frozen yogurt, you are the celery of desserts. Be ice cream, or be nothing.",
"Fishing relaxes me. It's like yoga, except I still get to kill something.",
"When I eat, it is the food that is scared.",
"Just give me all the bacon and eggs you have. Wait … I worry what you heard was, 'Give me a lot of bacon and eggs.' What I said was, give me all the bacon and eggs you have. Do you understand?",
"I've cried twice in my life. Once when I was 7 and hit by a school bus. And then again when I heard that Li'l Sebastian had passed.",
"Don't start chasing applause and acclaim. That way lies madness.",
"I call this turf 'n' turf. It's a 16-ounce T-bone and a 24-ounce porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American.",
"I'm a simple man. I like pretty, dark-haired women and breakfast food.",
"When people get too chummy with me, I like to call them by the wrong name to let them know I don't really care about them.",
"If there were more food and fewer people, this would be a perfect party.",
"That is a canvas sheet, the most versatile object known to man. It can be used to make tents, backpacks, shoes, stretchers, sails, tarpaulins, and I suppose, in the most dire of circumstances, it can be a surface on which to make art.",
"Any dog under 50 pounds is a cat, and cats are useless.",
"I regret nothing. The end.",
"I'd wish you the best of luck but I believe luck is a concept created by the weak to explain their failures.",
"Clear alcohols are for rich women on diets.",
"Crying: Acceptable at funerals and the Grand Canyon.",
"There are three acceptable haircuts: high and tight, crew cut, buzz cut.",
"Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.",
"On my deathbed, my final wish is to have my ex-wives rush to my side so I can use my dying breath to tell them both to go to hell one last time.",
"Normally, if given the choice between doing something and nothing, I'd choose to do nothing. But I will do something if it helps someone else do nothing. I'd work all night, if it meant nothing got done.",
"When I walked in this morning and saw that the flag was half-mast, I thought ‘All right, another bureaucrat ate it!'",
"I like Tom. He doesn't do a lot of work around here. He shows zero initiative. He's not a team player. He's never wanted to go that extra mile. Tom is exactly what I'm looking for in a government employee.",
"The whole point of this country is if you want to eat garbage, balloon up to 600 pounds and die of a heart attack at 43, you can! You are free to do so. To me, that's beautiful.",
"There is only one bad word: taxes.",
"Great job, everyone. The reception will be held in each of our individual houses, alone.",
"I have a hernia. I've had it for a while, and I've been ignoring it successfully. But uh, this morning, I made the mistake of sneezing. But as long as I sit still and don't move my head or torso, I'm good. I got this.",
"Literally everything is a weapon, son. That folder, in my hands, is far deadlier than this bow of yours.",
"Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating.",
"I would rather bleed out than sit here and talk about my feelings for 10 minutes.",
"Give 100 percent. One-hundred-and-ten percent is impossible. Only idiots recommend that.",
"Never half-ass two things. Whole-ass one thing.",
"Keep your tears in your eyes—where they belong.",
"You had me at ‘Meat Tornado.'",
"My first ex-wife's name is Tammy. My second ex-wife's name is Tammy. My Mom's name is Tamara … she goes by Tammy.",
"Sting like a bee, but do not float like a butterfly. That's ridiculous.",
"You've accidentally given me the food that my food eats.",
"Put some alcohol in your mouth to block with words from coming out.",
"Friends: one to three is sufficient.",
"The government is a greedy piglet that suckles on a taxpayer's teat until they have sore, chapped nipples.",
"I love being a father but there are a few things I miss: Silence. The absence of noise. One single moment undisturbed by the sounds of a children's program called Doc McStuffins.",
"It's pointless for a human to paint scenes of nature when they can go outside and stand in it.",
"An ideal night out, to me, is stepping onto my porch area and grilling up a thick slab of something's flesh and then popping in a highlight reel from the WNBA.",
"America: The only country that matters. If you want to experience other ‘cultures,' use an atlas or a ham radio.",
"It's always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain.",
"Fishing is for sport only. Fish meat is practically a vegetable.",
"One rage every three months is permitted. Try not to hurt anyone who doesn't deserve it.",
"I'll take that steak to go. Please and thank you.",
"The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy.",
"Barbecues should be about one thing: good shared meat.",
"I prefer quality over flash — that's why I refuse to write my signature in cursive.",
"Live your life how you want, but don't confuse drama with happiness.",
"I don't want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief.",
"People are idiots, Leslie."];
export default Quotes;
