import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Layout, Menu, Breadcrumb } from 'antd';

const { Header, Content, Footer } = Layout;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Salazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Salazar!
        </h1>
        <Link href = 'user'>

          <a>
            Go to User Interface
          </a>

        </Link>
        <Link href = 'speech'>

          <a>
            Go to speech
          </a>

        </Link>




      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}
