import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import LandingPage from '../components/homepage/LandingPage.js'
import { Layout, Menu, Breadcrumb } from 'antd';

const { Header, Content, Footer } = Layout;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Salazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage />

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div >
  )
}
