import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import SignUpForm from '../components/homepage/SignUpForm'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <SignUpForm />
        <Link href='/'>

          <a>
            Go to Landing page.
          </a>

        </Link>



      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}