import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sign up
        </h1>
        <Link href='/'>

          <a>
            Go to Landing page.
          </a>

        </Link>



      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}