import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import ScheduleCall from '../components/modals/ScheduleCall.js';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Salazar Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          User Interface
        </h1>
        <ScheduleCall/>
        <Link href = '/'>

          <a>
            Go to Landing page.
          </a>

        </Link>



      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}
