import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import ScheduleCall from '../components/modals/ScheduleCall.js';
import { Button } from 'antd';



export default function Home() {
  const [showScheduleCall, setShowScheduleCall] = useState(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Salazar Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          User Interface
        </h1>
        <Button onClick = {()=> {setShowScheduleCall( <ScheduleCall close = {setShowScheduleCall}/>)}}>Schedule A Call</Button>

        {showScheduleCall}


        <Link href = '/'>

          <a>
            Go to Landing page.
          </a>

        </Link>



      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}
